### ISSUE TITLE
nix-flakes image does not have flakes enabled?

### ISSUE THREAD

**Issue by pinpox** [nix-community/docker-nixpkgs#18]
I'm trying to use the `nix-flakes` image to work with flakes in a CI pipeline (droneCI).
Trying to run commands that require experimental-features fails, even though I'm using the `nix-flakes` image, this is what I'm trying:

```
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: Show flake info
  image: nixpkgs/nix-flakes
  commands:
  - nix flake show
  - nix flake info
  - nix flake list-inputs
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
```

I get the following error in the output:

```
latest: Pulling from nixpkgs/nix-flakes
Digest: sha256:198cc4134cf0607571fa36c7470ffc80374bb1decc153c850d6691f409fba011
Status: Image is up to date for nixpkgs/nix-flakes:latest
+ nix flake show
error: --- Error --- nix
experimental Nix feature 'nix-command' is disabled; use '--experimental-features nix-command' to override
```

What is the way to use flakes with the docker images? Am I using the correct image at all?
